PhotoSharingApplication/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{
    public class CommentController : Controller
    {
        private IPhotoSharingContext context;

        //Constructors
        public CommentController()
        {
            context = new PhotoSharingContext();
        }

        public CommentController(IPhotoSharingContext Context)
        {
            context = Context;
        }

        //
        // GET: A Partial View for displaying in the Photo Details view
        [ChildActionOnly] //This attribute means the action cannot be accessed from the browser's address bar
        public PartialViewResult _CommentsForPhoto(int PhotoId)
        {
            //The comments for a particular photo have been requested. Get those comments.
            var comments = from c in context.Comments
                           where c.PhotoID == PhotoId
                           select c;
            //Save the PhotoID in the ViewBag because we'll need it in the view
            ViewBag.PhotoId = PhotoId;
            return PartialView(comments.ToList());
        }

        //
        //POST: This action creates the comment when the AJAX comment create tool is used
        [HttpPost]
        public PartialViewResult _CommentsForPhoto(Comment comment, int PhotoId)
        {

            //Save the new comment
            context.Add<Comment>(comment);
            context.SaveChanges();

            //Get the updated list of comments
            var comments = from c in context.Comments
                           where c.PhotoID == PhotoId
                           select c;
            //Save the PhotoID in the ViewBag because we'll need it in the view
            ViewBag.PhotoId = PhotoId;
            //Return the view with the new list of comments
            return PartialView("_CommentsForPhoto", comments.ToList());
        }

        //
        // GET: /Comment/_Create. A Partial View for displaying the create comment tool as a AJAX partial page update
        [Authorize]
        public PartialViewResult _Create(int PhotoId)
        {
            //Create the new comment
            Comment newComment = new Comment();
            newComment.PhotoID = PhotoId;

            ViewBag.PhotoID = PhotoId;
            return PartialView("_CreateAComment");
        }



        //
        // GET: /Comment/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Comment comment = context.FindCommentById(id);
            ViewBag.PhotoID = comment.PhotoID;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = context.FindCommentById(id);
            context.Delete<Comment>(comment);
            context.SaveChanges();
            return RedirectToAction("Display", "Photo", new { id = comment.PhotoID });
        }

    }
}

PhotoSharingApplication/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Globalization;
using PhotoSharingApplication.GeocodeService;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{
    [HandleError(View = "Error")]
    [ValueReporter]
    public class PhotoController : Controller
    {
        private IPhotoSharingContext context;

        //Constructors
        public PhotoController()
        {
            context = new PhotoSharingContext();
        }

        public PhotoController(IPhotoSharingContext Context)
        {
            context = Context;
        }

        //
        // GET: /Photo/
        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;

            if (number == 0)
            {
                photos = context.Photos.ToList();
            }
            else
            {
                photos = (from p in context.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToList();
            }

            return PartialView("_PhotoGallery", photos);
        }

        public ActionResult Display(int id)
        {
            Photo photo = context.FindPhotoById(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);
        }

        public ActionResult DisplayByTitle(string title)
        {
            Photo photo = context.FindPhotoByTitle(title);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Display", photo);
        }

        [Authorize]
        public ActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(Photo photo, HttpPostedFileBase image)
        {
            photo.UserName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name);
            photo.CreatedDate = DateTime.Today;
            if (photo.Location != "")
            {
                string stringLatLong = CheckLocation(photo.Location);
                if (stringLatLong.StartsWith("Success"))
                {
                    char[] splitChars = {':'};
                    string[] coordinates = stringLatLong.Split(splitChars);
                    photo.Latitude = coordinates[1];
                    photo.Longitude = coordinates[2];
                }
            }
            if (!ModelState.IsValid)
            {
                return View("Create", photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.ContentLength];
                    image.InputStream.Read(photo.PhotoFile, 0, image.ContentLength);
                }
                context.Add<Photo>(photo);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            Photo photo = context.FindPhotoById(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Delete", photo);
        }

        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Photo photo = context.FindPhotoById(id);
            context.Delete<Photo>(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage(int id)
        {
            Photo photo = context.FindPhotoById(id);
            if (photo != null)
            {
                return File(photo.PhotoFile, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult SlideShow()
        {
            return View("SlideShow", context.Photos.ToList());
        }

        public ActionResult FavoritesSlideshow()
        {
            List<Photo> favPhotos = new List<Photo>();
            List<int> favoriteIds = Session["Favorites"] as List<int>;
            if (favoriteIds == null)
            {
                favoriteIds = new List<int>();
            }
            Photo currentPhoto;

            foreach (int favID in favoriteIds)
            {
                currentPhoto = context.FindPhotoById(favID);
                if (currentPhoto != null)
                {
                    favPhotos.Add(currentPhoto);
                }
            }

            return View("SlideShow", favPhotos);
        }

        public ContentResult AddFavorite(int PhotoID)
        {
            List<int> favorites = Session["Favorites"] as List<int>;
            if (favorites == null)
            {
                favorites = new List<int>();
            }
            favorites.Add(PhotoID);
            Session["Favorites"] = favorites;
            return Content("The picture has been added to your favorites", "text/plain", System.Text.Encoding.Default);
        }

        private string CheckLocation(string location)
        {
            string response = "";
            try
            {
                
                response = GetLocation(location);
            }
            catch (Exception e)
            {
                response = "Error: " + e.Message;
            }
            return response;
        }

        private string GetLocation(string address)
        {
            string results = string.Empty;

            string key = "AjWJ0toEszyIarecyQlnVMkqPJErH5v3iJnV51XSBXzfMwMR4rOVETwGUDmTPYMD";

            try
            {
                //Create the geocode request, set the access key and the address to query
                GeocodeRequest geocodeRequest = new GeocodeRequest();
                geocodeRequest.Credentials = new GeocodeService.Credentials();
                geocodeRequest.Credentials.ApplicationId = key;
                geocodeRequest.Query = address;

                //Create a filter to return only high confidence results
                ConfidenceFilter[] filters = new ConfidenceFilter[1];
                filters[0] = new ConfidenceFilter();
                filters[0].MinimumConfidence = Confidence.High;

                //Apply the filter to the request
                GeocodeOptions options = new GeocodeOptions();
                options.Filters = filters;
                geocodeRequest.Options = options;

                //Make the request
                GeocodeServiceClient client = new GeocodeServiceClient("BasicHttpBinding_IGeocodeService");
                GeocodeResponse response = client.Geocode(geocodeRequest);

                if (response.Results.Length > 0)
                {
                    results = String.Format("Success: {0}:{1}",
                        response.Results[0].Locations[0].Latitude,
                        response.Results[0].Locations[0].Longitude);
                }
                else
                {
                    results = "No Results Found";
                }
            }
            catch (Exception e)
            {
                results = "Geocoding Error: " + e.Message;
            }

            return results;

        }
    }
}

PhotoSharingApplication/Views/Shared/_CommentsForPhoto.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Comment>

<h3>Comments</h3>

@using (Ajax.BeginForm("_CommentsForPhoto",
                        new { PhotoId = ViewBag.PhotoId },
                        new AjaxOptions { UpdateTargetId = "comments-tool" }))
{

<div id="comments-tool">
    <div id="all-comments">
    @foreach (var item in Model)
    {
        <div class="photo-comment">

            <div class="photo-comment-from">
                From:
                @Html.DisplayFor(modelItem => item.UserName)
            </div>

            <div class="photo-comment-subject">
                @Html.DisplayNameFor(model => model.Subject):
                @Html.DisplayFor(modelItem => item.Subject)
            </div>

            <div class="photo-comment-body">
                @Html.DisplayFor(modelItem => item.Body)
            </div>

            @Html.ActionLink("Delete This Comment", "Delete", new { id = item.CommentID })

        </div>
    }
    </div>

    <div id="addcomment" class="add-comment-box">
        @if (Request.IsAuthenticated)
        {
            @Html.Action("_Create", "Comment", new { PhotoID = ViewBag.PhotoId })
        }
        else
        {
            @Html.ActionLink("To comment you must log in", "Login", "Account")
        }
    </div>
</div>
}

PhotoSharingApplication/Views/Shared/_CreateAComment.cshtml
@model PhotoSharingApplication.Models.Comment

@Html.ValidationSummary(true)

<div class="add-comment-tool">

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Subject)
            @Html.ValidationMessageFor(model => model.Subject)
        </span>
    </div>

    <div>
        <span class="editor-label">
            @Html.LabelFor(model => model.Body)
        </span>
        <span class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </span>
    </div>

    <p>
        <input type="submit" value="Create" />
    </p>

</div>

PhotoSharingApplication/Views/Shared/_MainLayout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css" />
</head>
<body>

    <h1 class="site-page-title">
        Adventure Works<br /> 
        Photo Sharing <br />
        Mobile Site
    </h1>
    <div class="clear-floats" />

    <div id="topmenu">
        @Html.MvcSiteMap().Menu(false, true, true)
    </div>
    
    <div id="breadcrumb">
        Current Location: @Html.MvcSiteMap().SiteMapPath()
    </div>
    
    <div>
        @RenderBody()
    </div>

</body>
</html>

PhotoSharingApplication/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.8.0.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.0/jquery-ui.min.js" type="text/javascript"></script>
</head>
<body>

    <h1 class="site-page-title">Adventure Works Photo Sharing</h1>
    <div class="login-controls">
        @if (Request.IsAuthenticated) {
            <div>
                Hello, @System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(User.Identity.Name).
                @Html.ActionLink("Log Off", "LogOff", "Account")
                @Html.ActionLink("Reset", "ResetPassword", "Account")
            </div>
        } else {
            <div>
                @Html.ActionLink("Log In", "Login", "Account")
                @Html.ActionLink("Register", "Register", "Account")
            </div>
        }
    </div>
    <div class="clear-floats" />

    <div id="topmenu">
        @Html.MvcSiteMap().Menu(false, true, true)
    </div>
    
    <div id="breadcrumb">
        Current Location: @Html.MvcSiteMap().SiteMapPath()
    </div>

    @if (Session["Favorites"] != null) {
        <div id="favourites-link">
            @Html.ActionLink("Favorite Photos", "FavoritesSlideshow", "Photo")
        </div>
    }
    
    <div>
        @RenderBody()
    </div>

</body>
</html>

PhotoSharingApplication/Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model)
{
    
<div class="photo-index-card">
    <h3>"@item.Title"</h3>
    
    @if (item.PhotoFile != null)
    {
        <img class="photo-index-card-img" src="@Url.Action("GetImage", "Photo", new { id = item.PhotoID })" />
    }
    
    <div class="photo-metadata">
        
        <div>
            <span class="display-label">
                Created By:
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.UserName)
            </span>
        </div>
    
        <div>
            <span class="display-label">
                Created On:
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.CreatedDate)
            </span>
        </div>

    </div>
    
    @Html.ActionLink("Display", "Display", new { id = item.PhotoID }) |
    @Html.ActionLink("Delete", "Delete", new { id = item.PhotoID })

    </div>
}